apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: test
spec:
  flows:
    - route:
        from:
          uri: netty-http:http://0.0.0.0:8080/camel/api/post
          steps:
            - to:
                uri: >-
                  atlasmap:file:/workspace/EazyIntegration/mapping/remote-post-http-request.adm
            - to:
                uri: undertow
                parameters:
                  useStreaming: true
                  sendToAll: false
            - to:
                uri: >-
                  atlasmap:file:/workspace/EazyIntegration/mapping/remote-post-http-response.adm
          parameters:
            keepAlive: true
            bridgeEndpoint: true
            httpMethodRestrict: POST
            traceEnabled: true
        trace: true
        id: http-post-details
        description: Post Details From Http Bin