apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: remote-post-http.yaml
spec:
  flows:
    - route:
        from:
          uri: netty-http:http://0.0.0.0:8080/camel/api/post
          steps:
            - to:
                uri: >-
                  atlasmap:file:/workspace/EazyIntegration/mapping/remote-post-http-request.adm
            - to:
                uri: undertow:http://httpbin.org/post
                parameters:
                  useStreaming: true
                  sendToAll: false
            - to:
                uri: >-
                  atlasmap:file:/workspace/EazyIntegration/mapping/remote-post-http-response.adm
                parameters:
                  allowContextMapAll: false
                  contentCache: false
                  forceReload: false
                  lazyStartProducer: true
          parameters:
            bridgeEndpoint: true
            httpMethodRestrict: POST
            traceEnabled: true
            keepAlive: true
            sync: true
        id: http-get-details
        description: Get Details From Http Bin
        trace: true
  dependencies:
    - mvn:org.apache.camel:camel-atlasmap:3.20.1